# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aBYEVUbuOyEPdvWC6nMOlDbrLI3t0MRj
"""

!pip install streamlit

import os

os.listdir("/")

from google.colab import files
uploaded = files.upload()

import pandas as pd

df = pd.read_csv(list(uploaded.keys())[0])
df.head()

import pandas as pd
import os

possible_paths = [
    "/mnt/data/ipl - master.csv",
    "/content/ipl - master.csv",
    "ipl - master.csv"
]

for path in possible_paths:
    if os.path.exists(path):
        df = pd.read_csv(path)
        print(f"Loaded file from: {path}")
        break
else:
    raise FileNotFoundError("Dataset not found. Please upload the CSV.")

print(df.shape)
print(df.columns)

print(df.columns.tolist())

import streamlit as st
import pandas as pd

# Load data
df = pd.read_csv("ipl - master.csv")

# Final Score
df["Final_Player_Score"] = (
    0.30 * df["Batting_Impact_Score"].fillna(0) +
    0.20 * df["Consistency_Score"] +
    0.20 * df["All_Rounder_Value_Index"] +
    0.15 * df["Cost_Efficiency_Ratio"] +
    0.10 * df["Team_Home_Win_Percentage"] +
    0.05 * df["Matches_Played"]
)

# Selection Function
def select_dream11_team(df, budget=125):
    team = []
    total_budget = 0
    overseas_count = 0

    role_limits = {
        "Pure Batsman": 2,
        "Pure Bowler": 2,
        "AllRounder": 1
    }

    role_count = {k: 0 for k in role_limits}

    df_sorted = df.sort_values("Final_Player_Score", ascending=False)

    for _, row in df_sorted.iterrows():
        if len(team) == 7:
            break

        if total_budget + row["Sold_Price_In_Crores"] > budget:
            continue

        if row["Nationality"] == "Overseas" and overseas_count >= 3:
            continue

        role = row["Role"]
        if role in role_limits and role_count[role] >= role_limits[role]:
            continue

        team.append(row)
        total_budget += row["Sold_Price_In_Crores"]

        if row["Nationality"] == "Overseas":
            overseas_count += 1
        if role in role_count:
            role_count[role] += 1

    return pd.DataFrame(team), total_budget

# Dashboard UI
st.set_page_config(page_title="IPL Dream11 Optimizer", layout="wide")

st.title("🏏 IPL Dream11 Team Optimizer")
st.subheader("Data-Driven Player Selection under ₹125 Cr")

budget = st.slider("Select Budget (₹ Cr)", 50, 125, 125)

team_df, spent = select_dream11_team(df, budget)

st.metric("Total Budget Spent (₹ Cr)", round(spent, 2))
st.metric("Remaining Budget (₹ Cr)", round(budget - spent, 2))

st.markdown("### 🧩 Selected Dream11 Team (7 Players)")
st.dataframe(
    team_df[[
        "Player Name",
        "Role",
        "Nationality",
        "Sold_Price_In_Crores",
        "Final_Player_Score"
    ]].sort_values("Final_Player_Score", ascending=False),
    use_container_width=True
)

st.markdown("### 📊 Role Distribution")
st.bar_chart(team_df["Role"].value_counts())

df["Final_Player_Score"] = (
    0.30 * df["Batting_Impact_Score"].fillna(0) +
    0.20 * df["Consistency_Score"] +
    0.20 * df["All_Rounder_Value_Index"] +
    0.15 * df["Cost_Efficiency_Ratio"] +
    0.10 * df["Team_Home_Win_Percentage"] +
    0.05 * df["Matches_Played"]
)

def select_dream11_team(df, budget=125):
    team = []
    total_budget = 0
    overseas_count = 0

    role_limits = {
        "Pure Batsman": 2,
        "Pure Bowler": 2,
        "AllRounder": 1
    }
    role_count = {k: 0 for k in role_limits}

    df_sorted = df.sort_values("Final_Player_Score", ascending=False)

    for _, row in df_sorted.iterrows():
        if len(team) == 7:
            break
        if total_budget + row["Sold_Price_In_Crores"] > budget:
            continue
        if row["Nationality"] == "Overseas" and overseas_count >= 3:
            continue
        if row["Role"] in role_limits and role_count[row["Role"]] >= role_limits[row["Role"]]:
            continue

        team.append(row)
        total_budget += row["Sold_Price_In_Crores"]

        if row["Nationality"] == "Overseas":
            overseas_count += 1
        if row["Role"] in role_count:
            role_count[row["Role"]] += 1

    return pd.DataFrame(team), total_budget

print("Using player column:", player_col)

team_df, spent = select_dream11_team(df, budget=125)

from IPython.display import display

display(
    team_df[[
        player_col,
        "Role",
        "Nationality",
        "Sold_Price_In_Crores",
        "Final_Player_Score"
    ]].sort_values("Final_Player_Score", ascending=False)
)

print("Total Budget Used:", round(spent, 2))
print("Remaining Budget:", round(125 - spent, 2))

print(df.columns.tolist())

player_col = "Player Name"
print("Using player column:", player_col)

# safety check
assert player_col in df.columns

team_df, spent = select_dream11_team(df, budget=125)

from IPython.display import display

display(
    team_df[[
        player_col,
        "Role",
        "Nationality",
        "Sold_Price_In_Crores",
        "Final_Player_Score"
    ]].sort_values("Final_Player_Score", ascending=False)
)

print("Total Budget Used (₹ Cr):", round(spent, 2))
print("Remaining Budget (₹ Cr):", round(125 - spent, 2))

import matplotlib.pyplot as plt

team_df["Role"].value_counts().plot(
    kind="bar",
    title="Dream11 Team – Role Distribution"
)
plt.show()



