# -*- coding: utf-8 -*-
"""ipl.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14SSlkmuW33bXJxmv_1W8_ZvGd2x2RNk3
"""

from google.colab import files

uploaded = files.upload()

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

df = pd.read_csv("ipl - master.csv")
df.info()
df.describe()

df = df.dropna(subset=["Performance_Tier"])
df = df[df["Matches_Played"] >= 5]

from sklearn.preprocessing import OneHotEncoder

cat_cols = ["Role", "Nationality"]
df = pd.get_dummies(df, columns=cat_cols, drop_first=True)

feature_cols = [
    "Batting_Impact_Score",
    "Bowling_Impact_Score",
    "Consistency_Score",
    "All_Rounder_Value_Index",
    "D/M_Ratio",
    "Matches_Played",
    "Cost_Efficiency_Ratio"
]

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor

X = df[feature_cols]
y = df["Sold_Price_In_Crores"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

model = RandomForestRegressor(n_estimators=200, random_state=42)
model.fit(X_train, y_train)

df["Expected_Price"] = model.predict(X)
df["Value_Gap"] = df["Expected_Price"] - df["Sold_Price_In_Crores"]

undervalued = df[
    (df["Value_Gap"] > 0) &
    (df["Performance_Tier"].isin(["Top", "Mid"]))
]

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

X_class = df[feature_cols]
y_class = df["Performance_Tier"]

Xc_train, Xc_test, yc_train, yc_test = train_test_split(
    X_class,
    y_class,
    test_size=0.2,
    random_state=42,
    stratify=y_class
)

clf = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    class_weight="balanced"
)

clf.fit(Xc_train, yc_train)

from sklearn.metrics import classification_report, confusion_matrix

yc_pred = clf.predict(Xc_test)

print(confusion_matrix(yc_test, yc_pred))
print(classification_report(yc_test, yc_pred))

df["Home_Score"] = (
    0.5 * df["Batting_Impact_Score"] +
    0.5 * df["Team_Home_Win_Percentage"]
)

import pandas as pd

importance = pd.Series(
    model.feature_importances_,
    index=feature_cols
).sort_values(ascending=False)

importance

weights = importance / importance.sum()
weights

import shap

explainer = shap.TreeExplainer(model)
shap_values = explainer.shap_values(X_train)

shap.summary_plot(shap_values, X_train)

df["Final_Player_Score"] = (
    0.30 * df["Batting_Impact_Score"].fillna(0) +
    0.20 * df["Consistency_Score"] +
    0.20 * df["All_Rounder_Value_Index"] +
    0.15 * df["Cost_Efficiency_Ratio"] +
    0.10 * df["Team_Home_Win_Percentage"] +
    0.05 * df["Matches_Played"]
)

def select_dream11_team(df, budget=125):
    team = []
    total_budget = 0
    overseas_count = 0

    role_limits = {
        "Pure Batsman": 2,
        "Pure Bowler": 2,
        "AllRounder": 1
    }

    role_count = {
        "Pure Batsman": 0,
        "Pure Bowler": 0,
        "AllRounder": 0
    }

    df_sorted = df.sort_values("Final_Player_Score", ascending=False)

    for _, row in df_sorted.iterrows():
        role = row["Role"]
        price = row["Sold_Price_In_Crores"]

        if len(team) == 7:
            break

        if total_budget + price > budget:
            continue

        if row["Nationality"] == "Overseas" and overseas_count >= 3:
            continue

        if role in role_limits and role_count[role] >= role_limits[role]:
            continue

        team.append(row)
        total_budget += price

        if row["Nationality"] == "Overseas":
            overseas_count += 1

        if role in role_count:
            role_count[role] += 1

    return pd.DataFrame(team), total_budget

